name: Deploy App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Create .env file
        uses: SpicyPizza/create-envfile@v2.0.3
        with:
          envkey_NODE_ENV: ${{ secrets.NODE_ENV }}
          envkey_PORT: ${{ secrets.PORT }}
          envkey_TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          envkey_TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
          envkey_TWILIO_PHONE_NUMBER: ${{ secrets.TWILIO_PHONE_NUMBER }}
          envkey_OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          envkey_GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          envkey_GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          envkey_GOOGLE_REDIRECT_URI: ${{ secrets.GOOGLE_REDIRECT_URI }}
          envkey_CALENDLY_URL: ${{ secrets.CALENDLY_URL }}
          envkey_HARVEY_PHONE_NUMBER: ${{ secrets.HARVEY_PHONE_NUMBER }}
          envkey_STREAM_URL: ${{ secrets.STREAM_URL }}
          envkey_JWT_SECRET: ${{ secrets.JWT_SECRET }}
          envkey_ACCESS_TOKEN_EXPIRES_IN: ${{ secrets.ACCESS_TOKEN_EXPIRES_IN }}
          directory: .
          file_name: .env

      - name: Install dependencies with Yarn
        run: yarn install

      - name: Build application with limited memory
        run: NODE_OPTIONS="--max-old-space-size=1536" yarn build

      - name: Install PM2 globally
        run: yarn global add pm2

      - name: Start app with PM2
        run: pm2 restart astro_project || pm2 start dist/server.js --name astro_project
